app:
  system: russian-passport
  small: rfp
  ext: 9099
db:
  url:
  driver:
  user:
  pw:
  leha:
    url:
    user:
    pw:
    driver:
    nsi:
    nsiCit:
logging:
  level:
    com.miku.curler.service.Service: debug
sanya:
  db:
    url:
    driver:
    user:
    pw: